const uiIcons = {
    accessibility: 'ui/accessibility',
    add: 'ui/add',
    attachment: 'ui/attachment',
    bookmark: 'ui/bookmark',
    checkmark_cirle: 'ui/checkmark-circle',
    checkmark: 'ui/checkmark',
    close_circle: 'ui/close-circle',
    close: 'ui/close',
    cloud_download: 'ui/cloud-download',
    cloud_upload: 'ui/cloud-upload',
    cloud: 'ui/cloud',
    cog: 'ui/cog',
    double_checkmark: 'ui/double-checkmark',
    download: 'ui/download',
    edit: 'ui/edit',
    exit_full_screen: 'ui/exit-full-screen',
    eye: 'ui/eye',
    filter: 'ui/filter',
    full_screen: 'ui/full-screen',
    heart: 'ui/heart',
    help: 'ui/help',
    home: 'ui/home',
    information: 'ui/information',
    language: 'ui/language',
    layout_grid: 'ui/layout-grid',
    layout_list: 'ui/layout-list',
    link: 'ui/link',
    menu: 'ui/menu',
    options: 'ui/options',
    prohibition: 'ui/prohibition',
    reload: 'ui/reload',
    search: 'ui/search',
    settings: 'ui/settings',
    share: 'ui/share',
    star: 'ui/star',
    sync: 'ui/sync',
    tag: 'ui/tag',
}

const timeIcons = {
    alarm_clock: 'time/alarm-clock',
    cuckoo_clock: 'time/cuckoo-clock',
    day_calendar: 'time/day-calendar',
    hourglass: 'time/hourglass-1',
    hourglass_second: 'time/hourglass-2',
    kitchen_timer: 'time/kitchen-timer',
    month_calendar: 'time/month-calendar',
    notification_bell: 'time/notification-bell',
    pendulum_wall: 'time/pendulum-wall-clock',
    stopwatch: 'time/stopwatch',
    time: 'time/time-24-hrs',
    time_countdown: 'time/time-countdown',
    time_nonstop: 'time/time-nonstop',
    time_repeating: 'time/time-repeating',
    wrist_watch: 'time/wrist-watch',
}

const securityIcons = {
    account_protection: 'security/account-protection',
    closed_lock: 'security/closed-lock',
    encrypted_folder: 'security/encrypted-folder',
    incognito: 'security/incognito.pdf',
    intruder: 'security/intruder.pdf',
    key_certificate: 'security/key-certificate',
    open_lock: 'security/open-lock',
    password: 'security/password-1',
    password_two: 'security/password-2',
    protection_shield: 'security/protection-shield-1',
    protection_shield_two: 'security/protection-shield-2',
    secure_network: 'security/secure-network',
    security_camera: 'security/security-camera',
    vault: 'security/vault',
    wall: 'security/wall',
}

const peopleIcons = {
    angry_face: 'people/angry-face',
    confused_face: 'people/confused-face',
    grinning_face: 'people/grinning-face',
    neutral_face: 'people/neutral-face',
    people: 'people/people',
    person_add: 'people/person-add',
    person_check: 'people/person-check',
    person_female: 'people/person-female',
    person_female_enclosed: 'people/person-female-enclosed',
    person_male: 'people/person-male',
    person_male_enclosed: 'people/person-male-enclosed',
    person_remove: 'people/person-remove',
    person_target: 'people/person-target',
    sad_face: 'people/sad-face',
    smiling_face: 'people/smiling-face'
}

const businessIcons = {
    calculator: 'business/calculator',
    calendar: 'business/calendar',
    contract: 'business/contract',
    downward_trend: 'downward-business/trend',
    folder: 'business/folder',
    goals: 'business/goals',
    office: 'business/office',
    organization_chart: 'organization-business/chart',
    pie_chart: 'pie-business/chart',
    presentation: 'business/presentation',
    scale: 'business/scale',
    suitcase: 'business/suitcase',
    target: 'business/target',
    upward_trend: 'upward-business/trend',
    v_card: 'v-business/card',
}

const devicesIcons = {
    battery: 'devices/battery',
    camera: 'devices/camera',
    desktop_computer: -'devices/desktop-computer',
    game_controller: 'devices/game-controller',
    ipod: 'devices/ipod',
    keyboard: 'devices/keyboard',
    laptop: 'devices/laptop',
    mouse: 'devices/mouse',
    printer: 'devices/printer',
    router: 'devices/router',
    smartphone: 'devices/smartphone',
    smartwatch: 'devices/smartwatch',
    tablet: 'devices/tablet',
    tv: 'devices/tv',
    usb: 'devices/usb',
}

const educationIcons = {
    abacus: 'education/abacus',
    academic: 'education/academic',
    backpack: 'education/backpack',
    blackboard: 'education/blackboard',
    brain: 'education/brain',
    compass: 'education/compass',
    diploma: 'education/diploma',
    diploma_roll: 'education/diploma-2',
    microscope: 'education/microscope',
    ring: 'education/ring',
    ruler: 'education/ruler',
    school_bell: 'education/school-bell',
    school_bus: 'education/school-bus',
    school: 'education/school',
    schoolbag: 'education/schoolbag',
}

const mediaIcons = {
    controls_decrease_volume: 'media/controls-decrease-volume',
    controls_fast_forward: 'media/controls-fast-forward',
    controls_increase_volume: 'media/controls-increase-volume',
    controls_mute: 'media/controls-mute',
    controls_next: 'media/controls-next',
    controls_pause: 'media/controls-pause',
    controls_play: 'media/controls-play',
    controls_play_pause: 'media/controls-play-pause',
    controls_previous: 'media/controls-previous',
    controls_record: 'media/controls-record',
    controls_repeat: 'media/controls-repeat',
    controls_repeat_once: 'media/controls-repeat-once',
    controls_rewind: 'media/controls-rewind',
    controls_shuffle: 'media/controls-shuffle',
    controls_stop: 'media/controls-stop',
}

const medicalIcons = {
    ambulance: 'medical/ambulance',
    bandage: 'medical/bandage',
    blood: 'medical/blood-bag',
    bottle_of_pills: 'medical/bottle-of-pills',
    dna: 'medical/dna',
    first_aid_kit: 'medical/first-aid-kit',
    heart: 'medical/heart-rate',
    hospital: 'medical/hospital',
    medical_record: 'medical/medical-record',
    pill: 'medical/pill',
    stethoscope: 'medical/stethoscope',
    syringe: 'medical/syringe',
    test: 'medical/test-tube',
    tooth: 'medical/tooth',
    wheel: 'medical/wheel-chair',
}

const navigationIcons = {
    checkered_flag: 'navigation/checkered-flag',
    compass: 'navigation/compass',
    direction: 'navigation/direction',
    home: 'navigation/home',
    lighthouse: 'navigation/lighthouse',
    marker: 'navigation/marker',
    marker_on_map: 'navigation/marker-on-map',
    mobile_navigation_one: 'navigation/mobile-navigation-1',
    mobile_navigation_two: 'navigation/mobile-navigation-2',
    navigation_device: 'navigation/navigation-device',
    orientation: 'navigation/orientation',
    pin_on_map: 'navigation/pin-on-map',
    pushpin: 'navigation/pushpin',
    road_sign: 'navigation/road-sign',
    target: 'navigation/target',
}

const transportIcons = {
    airplane: 'transport/airplane',
    bicycle: 'transport/bicycle',
    boat: 'transport/boat',
    bus: 'transport/bus',
    car: 'transport/car',
    gondola: 'transport/gondola',
    helicopter: 'transport/helicopter',
    motorcycle: 'transport/motorcycle',
    pickup: 'transport/pickup',
    road: 'transport/road',
    speedboat: 'transport/speedboat',
    taxi: 'transport/taxi',
    tractor: 'transport/tractor',
    train: 'transport/train',
    van: 'transport/van',
}

const travelIcons = {
    backpack: 'travel/backpack',
    beach: 'travel/beach',
    camp_fire: 'travel/camp-fire',
    camper: 'travel/camper',
    compass: 'travel/compass',
    flip_flops: 'travel/flip-flops',
    hotel: 'travel/hotel',
    ice_cream: 'travel/ice-cream',
    passport: 'travel/passport',
    shirt: 'travel/shirt',
    suitcase: 'travel/suitcase',
    sunglasses: 'travel/sunglasses',
    swimming_shorts: 'travel/swimming-shorts',
    tent: 'travel/tent',
    trolley: 'travel/trolley',
}

const weatherIcons = {
    cloud: 'weather/cloud',
    cloud_fog: 'weather/cloud-fog',
    cloud_hail: 'weather/cloud-hail',
    cloud_lightning: 'weather/cloud-lightning',
    cloud_sun: 'weather/cloud-sun',
    fog: 'weather/fog',
    heavy_rain: 'weather/heavy-rain',
    lightning: 'weather/lightning',
    moon: 'weather/moon',
    rain: 'weather/rain',
    snow: 'weather/snow',
    sun: 'weather/sun',
    sunset: 'weather/sunset',
    temperature: 'weather/temperature',
    tornado: 'weather/tornado',
}

const arrowIcons = {
    arrow_angle_ccw_e: 'arrows/arrow-angle-ccw-e',
    arrow_angle_ccw_n: 'arrows/arrow-angle-ccw-n',
    arrow_angle_ccw_s: 'arrows/arrow-angle-ccw-s',
    arrow_angle_ccw_w: 'arrows/arrow-angle-ccw-w',
    arrow_angle_cw_e: 'arrows/arrow-angle-cw-e',
    arrow_angle_cw_n: 'arrows/arrow-angle-cw-n',
    arrow_angle_cw_s: 'arrows/arrow-angle-cw-s',
    arrow_angle_cw_w: 'arrows/arrow-angle-cw-w',
    arrow_angle_double_ended_e_s: 'arrows/arrow-angle-double-ended-e-s',
    arrow_angle_double_ended_n_e: 'arrows/arrow-angle-double-ended-n-e',
    arrow_angle_double_ended_n_w: 'arrows/arrow-angle-double-ended-n-w',
    arrow_angle_double_ended_w_s: 'arrows/arrow-angle-double-ended-w-s',
    arrow_big_e: 'arrows/arrow-big-e',
    arrow_big_n: 'arrows/arrow-big-n',
    arrow_big_s: 'arrows/arrow-big-s',
    arrow_big_w: 'arrows/arrow-big-w',
    arrow_circle_e: 'arrows/arrow-circle-e',
    arrow_circle_n: 'arrows/arrow-circle-n',
    arrow_circle_s: 'arrows/arrow-circle-s',
    arrow_circle_w: 'arrows/arrow-circle-w',
    arrow_double_e_w: 'arrows/arrow-double-e-w',
    arrow_double_ended_n_s: 'arrows/arrow-double-ended-n-s',
    arrow_double_ended_ne_sw: 'arrows/arrow-double-ended-ne-sw',
    arrow_double_ended_nw_se: 'arrows/arrow-double-ended-nw-se',
    arrow_double_ended_w_e: 'arrows/arrow-double-ended-w-e',
    arrow_double_n_s: 'arrows/arrow-double-n-s',
    arrow_double_ne_sw: 'arrows/arrow-double-ne-sw',
    arrow_double_nw_se: 'arrows/arrow-double-nw-se',
    arrow_double_s_n: 'arrows/arrow-double-s-n',
    arrow_double_se_nw: 'arrows/arrow-double-se-nw',
    arrow_double_sw_ne: 'arrows/arrow-double-sw-ne',
    arrow_double_w_e: 'arrows/arrow-double-w-e',
    arrow_e: 'arrows/arrow-e',
    arrow_hook_2_e: 'arrows/arrow-hook-2-e',
    arrow_hook_2_w: 'arrows/arrow-hook-2-w',
    arrow_hook_e: 'arrows/arrow-hook-e',
    arrow_hook_w: 'arrows/arrow-hook-w',
    arrow_n: 'arrows/arrow-n',
    arrow_ne: 'arrows/arrow-ne',
    arrow_nw: 'arrows/arrow-nw',
    arrow_omni_directional: 'arrows/arrow-omni-directional',
    arrow_omni_directional_two: 'arrows/arrow-omni-directional-2',
    arrow_s: 'arrows/arrow-s',
    arrow_se: 'arrows/arrow-se',
    arrow_square_e: 'arrows/arrow-square-e',
    arrow_square_n: 'arrows/arrow-square-n',
    arrow_square_s: 'arrows/arrow-square-s',
    arrow_square_w: 'arrows/arrow-square-w',
    arrow_sw: 'arrows/arrow-sw',
    arrow_w: 'arrows/arrow-w',
    caret_circle_e: 'arrows/caret-circle-e',
    caret_circle_n: 'arrows/caret-circle-n',
    caret_circle_s: 'arrows/caret-circle-s',
    caret_circle_w: 'arrows/caret-circle-w',
    chevron_e: 'arrows/chevron-e',
    chevron_n: 'arrows/chevron-n',
    chevron_s: 'arrows/chevron-s',
    chevron_w: 'arrows/chevron-w',
}


export const FieldGroupIcons = {
    ...uiIcons,
    ...timeIcons,
    ...businessIcons,
    ...securityIcons,
    ...peopleIcons,
    ...devicesIcons,
    ...educationIcons,
    ...mediaIcons,
    ...medicalIcons,
    ...navigationIcons,
    ...transportIcons,
    ...travelIcons,
    ...weatherIcons,
    ...arrowIcons
}
