const uiFolder = 'ui';
const uiIcons = {
    accessibility: `${uiFolder}/accessibility`,
    add: `${uiFolder}/add`,
    attachment: `${uiFolder}/attachment`,
    bookmark: `${uiFolder}/bookmark`,
    checkmark_cirle: `${uiFolder}/checkmark-circle`,
    checkmark: `${uiFolder}/checkmark`,
    close_circle: `${uiFolder}/close-circle`,
    close: `${uiFolder}/close`,
    cloud_download: `${uiFolder}/cloud-download`,
    cloud_upload: `${uiFolder}/cloud-upload`,
    cloud: `${uiFolder}/cloud`,
    cog: `${uiFolder}/cog`,
    double_checkmark: `${uiFolder}/double-checkmark`,
    download: `${uiFolder}/download`,
    edit: `${uiFolder}/edit`,
    exit_full_screen: `${uiFolder}/exit-full-screen`,
    eye: `${uiFolder}/eye`,
    filter: `${uiFolder}/filter`,
    full_screen: `${uiFolder}/full-screen`,
    heart: `${uiFolder}/heart`,
    help: `${uiFolder}/help`,
    home: `${uiFolder}/home`,
    information: `${uiFolder}/information`,
    language: `${uiFolder}/language`,
    layout_grid: `${uiFolder}/layout-grid`,
    layout_list: `${uiFolder}/layout-list`,
    link: `${uiFolder}/link`,
    menu: `${uiFolder}/menu`,
    options: `${uiFolder}/options`,
    prohibition: `${uiFolder}/prohibition`,
    reload: `${uiFolder}/reload`,
    search: `${uiFolder}/search`,
    settings: `${uiFolder}/settings`,
    share: `${uiFolder}/share`,
    star: `${uiFolder}/star`,
    sync: `${uiFolder}/sync`,
    tag: `${uiFolder}/tag`,
}

const timeFolder = 'time';
const timeIcons = {
    alarm_clock: `${timeFolder}/alarm-clock`,
    cuckoo_clock: `${timeFolder}/cuckoo-clock`,
    day_calendar: `${timeFolder}/day-calendar`,
    hourglass: `${timeFolder}/hourglass-1`,
    hourglass_second: `${timeFolder}/hourglass-2`,
    kitchen_timer: `${timeFolder}/kitchen-timer`,
    month_calendar: `${timeFolder}/month-calendar`,
    notification_bell: `${timeFolder}/notification-bell`,
    pendulum_wall: `${timeFolder}/pendulum-wall-clock`,
    stopwatch: `${timeFolder}/stopwatch`,
    time: `${timeFolder}/time-24-hrs`,
    time_countdown: `${timeFolder}/time-countdown`,
    time_nonstop: `${timeFolder}/time-nonstop`,
    time_repeating: `${timeFolder}/time-repeating`,
    wrist_watch: `${timeFolder}/wrist-watch`,
}

const audioFolder = 'audio';
const audioIcons = {
    beamed_notes: `${audioFolder}/beamed-notes`,
    cassette: `${audioFolder}/cassette`,
    drum_machine: `${audioFolder}/drum-machine`,
    faders: `${audioFolder}/faders`,
    guitar: `${audioFolder}/guitar`,
    headphones: `${audioFolder}/headphones`,
    jack_plug: `${audioFolder}/jack-plug`,
    keyboard: `${audioFolder}/keyboard`,
    kick_drum: `${audioFolder}/kick-drum`,
    microphone: `${audioFolder}/microphone`,
    playlist: `${audioFolder}/playlist`,
    quaver_note: `${audioFolder}/quaver-note`,
    speaker: `${audioFolder}/speaker`,
    vinyl_record: `${audioFolder}/vinyl-record`,
    waveform: `${audioFolder}/waveform`,
}

const beautyFolder = 'beauty';
const beautyIcons = {
  comb: `${beautyFolder}/comb`,
  fragrance: `${beautyFolder}/fragrance`,
  hair_dryer: `${beautyFolder}/hair-dryer`,
  handheld_mirror: `${beautyFolder}/handheld-mirror`,
  lipstick: `${beautyFolder}/lipstick`,
  makeup_brush: `${beautyFolder}/makeup-brush`,
  mascara: `${beautyFolder}/mascara`,
  nail_polish: `${beautyFolder}/nail-polish`,
  nail: `${beautyFolder}/nail`,
  razor_blade: `${beautyFolder}/razor-blade`,
  safety_razor: `${beautyFolder}/safety-razor`,
  scissors: `${beautyFolder}/scissors`,
  shaving_machine: `${beautyFolder}/shaving-machine`,
  soap_dispenser: `${beautyFolder}/soap-dispenser`,
  straight_razor: `${beautyFolder}/straight-razor`,
}

const christmasFolder = 'christmas';
const christmasIcons = {
  candy_cane: `${christmasFolder}/candy-cane`,
  christmas_tree: `${christmasFolder}/christmas-tree`,
  clicking_glasses: `${christmasFolder}/clicking-glasses`,
  cracker: `${christmasFolder}/cracker`,
  decorations: `${christmasFolder}/decorations`,
  fireworks: `${christmasFolder}/fireworks`,
  gingerbread_man: `${christmasFolder}/gingerbread-man`,
  present: `${christmasFolder}/present`,
  reindeer: `${christmasFolder}/reindeer`,
  santa_claus: `${christmasFolder}/santa-claus`,
  santas_sleigh: `${christmasFolder}/santas-sleigh`,
  snow_globe: `${christmasFolder}/snow-globe`,
  snowman: `${christmasFolder}/snowman`,
  stocking: `${christmasFolder}/stocking`,
  tree_ornament: `${christmasFolder}/tree-ornament`,
}

const communicationFolder = 'communication';
const communicationIcons = {
  address_book: `${communicationFolder}/address-book`,
  archive: `${communicationFolder}/archive`,
  at: `${communicationFolder}/at`,
  chat: `${communicationFolder}/chat`,
  draft: `${communicationFolder}/draft`,
  envelope_open: `${communicationFolder}/envelope-open`,
  envelope: `${communicationFolder}/envelope`,
  headset: `${communicationFolder}/headset`,
  inbox: `${communicationFolder}/inbox`,
  mailbox: `${communicationFolder}/mailbox`,
  network: `${communicationFolder}/network`,
  newspaper: `${communicationFolder}/newspaper`,
  phone_call: `${communicationFolder}/phone-call`,
  radio_signal: `${communicationFolder}/radio-signal`,
  writing: `${communicationFolder}/writing`,
}

const connectivityFolder = 'connectivity';
const connectivityIcons = {
  bluetooth: `${connectivityFolder}/bluetooth`,
  chromecast: `${connectivityFolder}/chromecast`,
  ftp: `${connectivityFolder}/ftp`,
  link: `${connectivityFolder}/link`,
  network: `${connectivityFolder}/network`,
  plug: `${connectivityFolder}/plug`,
  radar: `${connectivityFolder}/radar`,
  reception: `${connectivityFolder}/reception`,
  relation: `${connectivityFolder}/relation`,
  remote: `${connectivityFolder}/remote`,
  rss: `${connectivityFolder}/rss`,
  simcard: `${connectivityFolder}/simcard`,
  usb: `${connectivityFolder}/usb`,
  web: `${connectivityFolder}/web`,
  wifi: `${connectivityFolder}/wifi`,
}

const drinksFolder = 'drinks';
const drinksIcons = {
  beer: `${drinksFolder}/beer`,
  champagne: `${drinksFolder}/champagne`,
  cocktail: `${drinksFolder}/cocktail`,
  coffee_cup: `${drinksFolder}/coffee-cup`,
  coffee: `${drinksFolder}/coffee`,
  iced_tea: `${drinksFolder}/iced-tea`,
  lemonade_jar: `${drinksFolder}/lemonade-jar`,
  long_drink: `${drinksFolder}/long-drink`,
  milkshake: `${drinksFolder}/milkshake`,
  soda_bottle: `${drinksFolder}/soda-bottle`,
  soda: `${drinksFolder}/soda`,
  tea_pot: `${drinksFolder}/tea-pot`,
  tea: `${drinksFolder}/tea`,
  whiskey_glass: `${drinksFolder}/whiskey-glass`,
  wine_bottle: `${drinksFolder}/wine-bottle`,
}

const ecommerceFolder = 'ecommerce';
const ecommerceIcons = {
  coin: `${ecommerceFolder}/coin`,
  creditcard: `${ecommerceFolder}/creditcard`,
  discount: `${ecommerceFolder}/discount`,
  gift: `${ecommerceFolder}/gift`,
  mobile_payment: `${ecommerceFolder}/mobile-payment`,
  paper_money: `${ecommerceFolder}/paper-money`,
  pricetag: `${ecommerceFolder}/pricetag`,
  receipt: `${ecommerceFolder}/receipt`,
  shopping_bag: `${ecommerceFolder}/shopping-bag`,
  shopping_basket: `${ecommerceFolder}/shopping-basket`,
  shopping_cart: `${ecommerceFolder}/shopping-cart`,
  store: `${ecommerceFolder}/store`,
  trolley: `${ecommerceFolder}/trolley`,
  voucher: `${ecommerceFolder}/voucher`,
  wallet: `${ecommerceFolder}/wallet`,
}

const environmentFolder = 'environment';
const environmentIcons = {
  charging_point: `${environmentFolder}/charging-point`,
  climate: `${environmentFolder}/climate`,
  eco_factory: `${environmentFolder}/eco-factory`,
  eco_plant: `${environmentFolder}/eco-plant`,
  ecology: `${environmentFolder}/ecology`,
  ecosystem: `${environmentFolder}/ecosystem`,
  electric_car: `${environmentFolder}/electric-car`,
  environmental_care: `${environmentFolder}/environmental-care`,
  green_home: `${environmentFolder}/green-home`,
  recycle_bin: `${environmentFolder}/recycle-bin`,
  recycle: `${environmentFolder}/recycle`,
  renewable_energy: `${environmentFolder}/renewable-energy`,
  solar_energy: `${environmentFolder}/solar-energy`,
  sustainable_lighting: `${environmentFolder}/sustainable-lighting`,
  wind_energy: `${environmentFolder}/wind-energy`,
}

const filesFolder = 'files';
const filesIcons = {
  add: `${filesFolder}/add`,
  bitmap: `${filesFolder}/bitmap`,
  camera: `${filesFolder}/camera`,
  cloud: `${filesFolder}/cloud`,
  code_1: `${filesFolder}/code-1`,
  code_2: `${filesFolder}/code-2`,
  code_3: `${filesFolder}/code-3`,
  confirm: `${filesFolder}/confirm`,
  file_3d: `${filesFolder}/file-3d`,
  file_audio: `${filesFolder}/file-audio`,
  file_compressed: `${filesFolder}/file-compressed`,
  file_database: `${filesFolder}/file-database`,
  file_design1: `${filesFolder}/file-design1`,
  file_design2: `${filesFolder}/file-design2`,
  file_font: `${filesFolder}/file-font`,
  file_help: `${filesFolder}/file-help`,
  file_image: `${filesFolder}/file-image`,
  file_rss: `${filesFolder}/file-rss`,
  file_settings: `${filesFolder}/file-settings`,
  file_spreadsheet: `${filesFolder}/file-spreadsheet`,
  file_vector: `${filesFolder}/file-vector`,
  file_video1: `${filesFolder}/file-video1`,
  file_video2: `${filesFolder}/file-video2`,
  layout: `${filesFolder}/layout`,
  locked: `${filesFolder}/locked`,
  pdf: `${filesFolder}/pdf`,
  presentation: `${filesFolder}/presentation`,
  recording: `${filesFolder}/recording`,
  remove: `${filesFolder}/remove`,
  web: `${filesFolder}/web`,
}

const foodFolder = 'food';
const foodIcons = {
  apple: `${foodFolder}/apple`,
  avocado: `${foodFolder}/avocado`,
  banana: `${foodFolder}/banana`,
  bread: `${foodFolder}/bread`,
  burger: `${foodFolder}/burger`,
  carrot: `${foodFolder}/carrot`,
  cheese: `${foodFolder}/cheese`,
  cookie: `${foodFolder}/cookie`,
  egg: `${foodFolder}/egg`,
  fish: `${foodFolder}/fish`,
  hotdog: `${foodFolder}/hotdog`,
  icecream: `${foodFolder}/icecream`,
  meat_on_bone: `${foodFolder}/meat-on-bone`,
  pizza: `${foodFolder}/pizza`,
  strawberry: `${foodFolder}/strawberry`,
}

const furnitureFolder = 'furniture';
const furnitureIcons = {
  bath_tub: `${furnitureFolder}/bath-tub`,
  bed: `${furnitureFolder}/bed`,
  book_case: `${furnitureFolder}/book-case`,
  bunk_bed: `${furnitureFolder}/bunk-bed`,
  cabinet: `${furnitureFolder}/cabinet`,
  chair: `${furnitureFolder}/chair`,
  closet: `${furnitureFolder}/closet`,
  coat_rack: `${furnitureFolder}/coat-rack`,
  couch: `${furnitureFolder}/couch`,
  door: `${furnitureFolder}/door`,
  lamp: `${furnitureFolder}/lamp`,
  mirror: `${furnitureFolder}/mirror`,
  office_chair: `${furnitureFolder}/office-chair`,
  shower: `${furnitureFolder}/shower`,
  sofa: `${furnitureFolder}/sofa`,
}

const identityFolder = 'identity';
const identityIcons = {
  aiga_female_symbol: `${identityFolder}/aiga-female-symbol`,
  aiga_male_symbol: `${identityFolder}/aiga-male-symbol`,
  bisexual_couple_sign: `${identityFolder}/bisexual-couple-sign`,
  face_id: `${identityFolder}/face-id`,
  female_couple_sign: `${identityFolder}/female-couple-sign`,
  female_sign: `${identityFolder}/female-sign`,
  fingerprint: `${identityFolder}/fingerprint`,
  gender_neutral_symbol: `${identityFolder}/gender-neutral-symbol`,
  id_card: `${identityFolder}/id-card`,
  intersex_sign: `${identityFolder}/intersex-sign`,
  iris_scan: `${identityFolder}/iris-scan`,
  male_couple_sign: `${identityFolder}/male-couple-sign`,
  male_female_couple_sign: `${identityFolder}/male-female-couple-sign`,
  male_sign: `${identityFolder}/male-sign`,
  transgender_sign: `${identityFolder}/transgender-sign`,
}

const imageEditingFolder = 'image-editing';
const imageEditingIcons = {
  aperture: `${imageEditingFolder}/aperture`,
  color: `${imageEditingFolder}/color`,
  contrast: `${imageEditingFolder}/contrast`,
  crop: `${imageEditingFolder}/crop`,
  curves: `${imageEditingFolder}/curves`,
  exposure: `${imageEditingFolder}/exposure`,
  eye_dropper: `${imageEditingFolder}/eye-dropper`,
  flash: `${imageEditingFolder}/flash`,
  flip_horizontally: `${imageEditingFolder}/flip-horizontally`,
  flip_vertically: `${imageEditingFolder}/flip-vertically`,
  grid: `${imageEditingFolder}/grid`,
  histogram: `${imageEditingFolder}/histogram`,
  rotate_photo: `${imageEditingFolder}/rotate-photo`,
  saturation: `${imageEditingFolder}/saturation`,
  sharpen: `${imageEditingFolder}/sharpen`,
}

const landmarksFolder = 'landmarks';
const landmarksIcons = {
  big_ben: `${landmarksFolder}/big-ben`,
  burj_al_arab: `${landmarksFolder}/burj-al-arab`,
  christ_the_redeemer: `${landmarksFolder}/christ-the-redeemer`,
  colloseum: `${landmarksFolder}/colloseum`,
  egyptian_pyramid: `${landmarksFolder}/egyptian-pyramid`,
  eiffel_tower: `${landmarksFolder}/eiffel-tower`,
  golden_gate_bridge: `${landmarksFolder}/golden-gate-bridge`,
  leaning_tower_of_pisa: `${landmarksFolder}/leaning-tower-of-pisa`,
  london_eye: `${landmarksFolder}/london-eye`,
  mesoamerican_pyramid: `${landmarksFolder}/mesoamerican-pyramid`,
  sphinx_of_giza: `${landmarksFolder}/sphinx-of-giza`,
  statue_of_liberty: `${landmarksFolder}/statue-of-liberty`,
  sydney_opera_house: `${landmarksFolder}/sydney-opera-house`,
  taj_mahal: `${landmarksFolder}/taj-mahal`,
  windmill: `${landmarksFolder}/windmill`,
}

const movieFolder = 'movie';
const movieIcons = {
  '3d_glasses': `${movieFolder}/3d-glasses`,
  clapperboard: `${movieFolder}/clapperboard`,
  directors_chair: `${movieFolder}/directors-chair`,
  film_roll: `${movieFolder}/film-roll`,
  film_strip: `${movieFolder}/film-strip`,
  hollywood_star: `${movieFolder}/hollywood-star`,
  movie_theater: `${movieFolder}/movie-theater`,
  movie_ticket: `${movieFolder}/movie-ticket`,
  oscar: `${movieFolder}/oscar`,
  popcorn: `${movieFolder}/popcorn`,
  television: `${movieFolder}/television`,
  theater: `${movieFolder}/theater`,
  vhs: `${movieFolder}/vhs`,
  video_camera: `${movieFolder}/video-camera`,
  video: `${movieFolder}/video`,
}

const politicsFolder = 'politics';
const politicsIcons = {
  candidate: `${politicsFolder}/candidate`,
  capitol: `${politicsFolder}/capitol`,
  debate: `${politicsFolder}/debate`,
  election_day: `${politicsFolder}/election-day`,
  election_programme: `${politicsFolder}/election-programme`,
  exit_polls: `${politicsFolder}/exit-polls`,
  megaphone: `${politicsFolder}/megaphone`,
  oath: `${politicsFolder}/oath`,
  opposition: `${politicsFolder}/opposition`,
  presidential_signature: `${politicsFolder}/presidential-signature`,
  protester: `${politicsFolder}/protester`,
  ribbon: `${politicsFolder}/ribbon`,
  uncle_sam_hat: `${politicsFolder}/uncle-sam-hat`,
  vote: `${politicsFolder}/vote`,
  voting: `${politicsFolder}/voting`,
}

const prideFolder = 'pride';
const prideIcons = {
  fist: `${prideFolder}/fist`,
  flag_agender: `${prideFolder}/flag-agender`,
  flag_aromantic: `${prideFolder}/flag-aromantic`,
  flag_asexual: `${prideFolder}/flag-asexual`,
  flag_bisexual: `${prideFolder}/flag-bisexual`,
  flag_demisexual: `${prideFolder}/flag-demisexual`,
  flag_genderfluid: `${prideFolder}/flag-genderfluid`,
  flag_genderqueer: `${prideFolder}/flag-genderqueer`,
  flag_intersex: `${prideFolder}/flag-intersex`,
  flag_lesbian: `${prideFolder}/flag-lesbian`,
  flag_non_binary: `${prideFolder}/flag-non-binary`,
  flag_pansexual: `${prideFolder}/flag-pansexual`,
  flag_pride: `${prideFolder}/flag-pride`,
  flag_transgender: `${prideFolder}/flag-transgender`,
  rainbow: `${prideFolder}/rainbow`,
}

const spaceFolder = 'space';
const spaceIcons = {
  alien: `${spaceFolder}/alien`,
  comet: `${spaceFolder}/comet`,
  constellation: `${spaceFolder}/constellation`,
  earth: `${spaceFolder}/earth`,
  falling_star: `${spaceFolder}/falling-star`,
  flag_on_planet: `${spaceFolder}/flag-on-planet`,
  moon: `${spaceFolder}/moon`,
  planet: `${spaceFolder}/planet`,
  rocket: `${spaceFolder}/rocket`,
  satellite: `${spaceFolder}/satellite`,
  saturn: `${spaceFolder}/saturn`,
  shuttle: `${spaceFolder}/shuttle`,
  suit: `${spaceFolder}/suit`,
  telescope: `${spaceFolder}/telescope`,
  ufo: `${spaceFolder}/ufo`,
}

const sportFolder = 'sport';
const sportIcons = {
  american_football: `${sportFolder}/american-football`,
  badminton: `${sportFolder}/badminton`,
  baseball: `${sportFolder}/baseball`,
  basketball: `${sportFolder}/basketball`,
  bowling: `${sportFolder}/bowling`,
  boxing: `${sportFolder}/boxing`,
  curling: `${sportFolder}/curling`,
  ice_skating: `${sportFolder}/ice-skating`,
  motor_racing: `${sportFolder}/motor-racing`,
  pingpong: `${sportFolder}/pingpong`,
  soccer: `${sportFolder}/soccer`,
  surf: `${sportFolder}/surf`,
  tennis: `${sportFolder}/tennis`,
  trophy: `${sportFolder}/trophy`,
  weight: `${sportFolder}/weight`,
}

const securityFolder = 'security';
const securityIcons = {
    account_protection: `${securityFolder}/account-protection`,
    closed_lock: `${securityFolder}/closed-lock`,
    encrypted_folder: `${securityFolder}/encrypted-folder`,
    incognito: `${securityFolder}/incognito`,
    intruder: `${securityFolder}/intruder`,
    key_certificate: `${securityFolder}/key-certificate`,
    open_lock: `${securityFolder}/open-lock`,
    password: `${securityFolder}/password-1`,
    password_two: `${securityFolder}/password-2`,
    protection_shield: `${securityFolder}/protection-shield-1`,
    protection_shield_two: `${securityFolder}/protection-shield-2`,
    secure_network: `${securityFolder}/secure-network`,
    security_camera: `${securityFolder}/security-camera`,
    vault: `${securityFolder}/vault`,
    wall: `${securityFolder}/wall`,
}

const peopleFolder = 'people';
const peopleIcons = {
    angry_face: `${peopleFolder}/angry-face`,
    confused_face: `${peopleFolder}/confused-face`,
    grinning_face: `${peopleFolder}/grinning-face`,
    neutral_face: `${peopleFolder}/neutral-face`,
    people: `${peopleFolder}/people`,
    person_add: `${peopleFolder}/person-add`,
    person_check: `${peopleFolder}/person-check`,
    person_female: `${peopleFolder}/person-female`,
    person_female_enclosed: `${peopleFolder}/person-female-enclosed`,
    person_male: `${peopleFolder}/person-male`,
    person_male_enclosed: `${peopleFolder}/person-male-enclosed`,
    person_remove: `${peopleFolder}/person-remove`,
    person_target: `${peopleFolder}/person-target`,
    sad_face: `${peopleFolder}/sad-face`,
    smiling_face: `${peopleFolder}/smiling-face`,
}

const businessFolder = 'business';
const businessIcons = {
    calculator: `${businessFolder}/calculator`,
    calendar: `${businessFolder}/calendar`,
    contract: `${businessFolder}/contract`,
    downward_trend: `${businessFolder}/downward-trend`,
    folder: `${businessFolder}/folder`,
    goals: `${businessFolder}/goals`,
    office: `${businessFolder}/office`,
    organization_chart: `${businessFolder}/organization-chart`,
    pie_chart: `${businessFolder}/pie-chart`,
    presentation: `${businessFolder}/presentation`,
    scale: `${businessFolder}/scale`,
    suitcase: `${businessFolder}/suitcase`,
    target: `${businessFolder}/target`,
    upward_trend: `${businessFolder}/upward-trend`,
    v_card: `${businessFolder}/v-card`,
}

const devicesFolder = 'devices';
const devicesIcons = {
    battery: `${devicesFolder}/battery`,
    camera: `${devicesFolder}/camera`,
    desktop_computer: `${devicesFolder}/desktop-computer`,
    game_controller: `${devicesFolder}/game-controller`,
    ipod: `${devicesFolder}/ipod`,
    keyboard: `${devicesFolder}/keyboard`,
    laptop: `${devicesFolder}/laptop`,
    mouse: `${devicesFolder}/mouse`,
    printer: `${devicesFolder}/printer`,
    router: `${devicesFolder}/router`,
    smartphone: `${devicesFolder}/smartphone`,
    smartwatch: `${devicesFolder}/smartwatch`,
    tablet: `${devicesFolder}/tablet`,
    tv: `${devicesFolder}/tv`,
    usb: `${devicesFolder}/usb`,
}

const educationFolder = 'education';
const educationIcons = {
    abacus: `${educationFolder}/abacus`,
    academic: `${educationFolder}/academic-cap`,
    backpack: `${educationFolder}/backpack`,
    blackboard: `${educationFolder}/blackboard`,
    brain: `${educationFolder}/brain`,
    compass: `${educationFolder}/compass`,
    diploma: `${educationFolder}/diploma-1`,
    diploma_roll: `${educationFolder}/diploma-2`,
    microscope: `${educationFolder}/microscope`,
    ring: `${educationFolder}/ring-stand`,
    ruler: `${educationFolder}/ruler`,
    school_bell: `${educationFolder}/school-bell`,
    school_bus: `${educationFolder}/school-bus`,
    school: `${educationFolder}/school`,
    schoolbag: `${educationFolder}/schoolbag`,
}

const mediaFolder = 'media';
const mediaIcons = {
    controls_decrease_volume: `${mediaFolder}/controls-decrease-volume`,
    controls_fast_forward: `${mediaFolder}/controls-fast-forward`,
    controls_increase_volume: `${mediaFolder}/controls-increase-volume`,
    controls_mute: `${mediaFolder}/controls-mute`,
    controls_next: `${mediaFolder}/controls-next`,
    controls_pause: `${mediaFolder}/controls-pause`,
    controls_play: `${mediaFolder}/controls-play`,
    controls_play_pause: `${mediaFolder}/controls-play-pause`,
    controls_previous: `${mediaFolder}/controls-previous`,
    controls_record: `${mediaFolder}/controls-record`,
    controls_repeat: `${mediaFolder}/controls-repeat`,
    controls_repeat_once: `${mediaFolder}/controls-repeat-once`,
    controls_rewind: `${mediaFolder}/controls-rewind`,
    controls_shuffle: `${mediaFolder}/controls-shuffle`,
    controls_stop: `${mediaFolder}/controls-stop`,
}

const medicalFolder = 'medical';
const medicalIcons = {
    ambulance: `${medicalFolder}/ambulance`,
    bandage: `${medicalFolder}/bandage`,
    blood: `${medicalFolder}/blood-bag`,
    bottle_of_pills: `${medicalFolder}/bottle-of-pills`,
    dna: `${medicalFolder}/dna`,
    first_aid_kit: `${medicalFolder}/first-aid-kit`,
    heart: `${medicalFolder}/heart-rate`,
    hospital: `${medicalFolder}/hospital`,
    medical_record: `${medicalFolder}/medical-record`,
    pill: `${medicalFolder}/pill`,
    stethoscope: `${medicalFolder}/stethoscope`,
    syringe: `${medicalFolder}/syringe`,
    test: `${medicalFolder}/test-tube`,
    tooth: `${medicalFolder}/tooth`,
    wheel: `${medicalFolder}/wheel-chair`,
}

const navigationFolder = 'navigation';
const navigationIcons = {
    checkered_flag: `${navigationFolder}/checkered-flag`,
    compass: `${navigationFolder}/compass`,
    direction: `${navigationFolder}/direction`,
    home: `${navigationFolder}/home`,
    lighthouse: `${navigationFolder}/lighthouse`,
    marker: `${navigationFolder}/marker`,
    marker_on_map: `${navigationFolder}/marker-on-map`,
    mobile_navigation_one: `${navigationFolder}/mobile-navigation-1`,
    mobile_navigation_two: `${navigationFolder}/mobile-navigation-2`,
    navigation_device: `${navigationFolder}/navigation-device`,
    orientation: `${navigationFolder}/orientation`,
    pin_on_map: `${navigationFolder}/pin-on-map`,
    pushpin: `${navigationFolder}/pushpin`,
    road_sign: `${navigationFolder}/road-sign`,
    target: `${navigationFolder}/target`,
}

const transportFolder = 'transport';
const transportIcons = {
    airplane: `${transportFolder}/airplane`,
    bicycle: `${transportFolder}/bicycle`,
    boat: `${transportFolder}/boat`,
    bus: `${transportFolder}/bus`,
    car: `${transportFolder}/car`,
    gondola: `${transportFolder}/gondola`,
    helicopter: `${transportFolder}/helicopter`,
    motorcycle: `${transportFolder}/motorcycle`,
    pickup: `${transportFolder}/pickup`,
    road: `${transportFolder}/road`,
    speedboat: `${transportFolder}/speedboat`,
    taxi: `${transportFolder}/taxi`,
    tractor: `${transportFolder}/tractor`,
    train: `${transportFolder}/train`,
    van: `${transportFolder}/van`,
}

const travelFolder = 'travel';
const travelIcons = {
    backpack: `${travelFolder}/backpack`,
    beach: `${travelFolder}/beach`,
    camp_fire: `${travelFolder}/camp-fire`,
    camper: `${travelFolder}/camper`,
    compass: `${travelFolder}/compass`,
    flip_flops: `${travelFolder}/flip-flops`,
    hotel: `${travelFolder}/hotel`,
    ice_cream: `${travelFolder}/ice-cream`,
    passport: `${travelFolder}/passport`,
    shirt: `${travelFolder}/shirt`,
    suitcase: `${travelFolder}/suitcase`,
    sunglasses: `${travelFolder}/sunglasses`,
    swimming_shorts: `${travelFolder}/swimming-shorts`,
    tent: `${travelFolder}/tent`,
    trolley: `${travelFolder}/trolley`,
}

const weatherFolder = 'weather';
const weatherIcons = {
    cloud: `${weatherFolder}/cloud`,
    cloud_fog: `${weatherFolder}/cloud-fog`,
    cloud_hail: `${weatherFolder}/cloud-hail`,
    cloud_lightning: `${weatherFolder}/cloud-lightning`,
    cloud_sun: `${weatherFolder}/cloud-sun`,
    fog: `${weatherFolder}/fog`,
    heavy_rain: `${weatherFolder}/heavy-rain`,
    lightning: `${weatherFolder}/lightning`,
    moon: `${weatherFolder}/moon`,
    rain: `${weatherFolder}/rain`,
    snow: `${weatherFolder}/snow`,
    sun: `${weatherFolder}/sun`,
    sunset: `${weatherFolder}/sunset`,
    temperature: `${weatherFolder}/temperature`,
    tornado: `${weatherFolder}/tornado`,
}

const arrowFolder = 'arrows';
const arrowIcons = {
    arrow_angle_ccw_e: `${arrowFolder}/arrow-angle-ccw-e`,
    arrow_angle_ccw_n: `${arrowFolder}/arrow-angle-ccw-n`,
    arrow_angle_ccw_s: `${arrowFolder}/arrow-angle-ccw-s`,
    arrow_angle_ccw_w: `${arrowFolder}/arrow-angle-ccw-w`,
    arrow_angle_cw_e: `${arrowFolder}/arrow-angle-cw-e`,
    arrow_angle_cw_n: `${arrowFolder}/arrow-angle-cw-n`,
    arrow_angle_cw_s: `${arrowFolder}/arrow-angle-cw-s`,
    arrow_angle_cw_w: `${arrowFolder}/arrow-angle-cw-w`,
    arrow_angle_double_ended_e_s: `${arrowFolder}/arrow-angle-double-ended-e-s`,
    arrow_angle_double_ended_n_e: `${arrowFolder}/arrow-angle-double-ended-n-e`,
    arrow_angle_double_ended_n_w: `${arrowFolder}/arrow-angle-double-ended-n-w`,
    arrow_angle_double_ended_w_s: `${arrowFolder}/arrow-angle-double-ended-w-s`,
    arrow_big_e: `${arrowFolder}/arrow-big-e`,
    arrow_big_n: `${arrowFolder}/arrow-big-n`,
    arrow_big_s: `${arrowFolder}/arrow-big-s`,
    arrow_big_w: `${arrowFolder}/arrow-big-w`,
    arrow_circle_e: `${arrowFolder}/arrow-circle-e`,
    arrow_circle_n: `${arrowFolder}/arrow-circle-n`,
    arrow_circle_s: `${arrowFolder}/arrow-circle-s`,
    arrow_circle_w: `${arrowFolder}/arrow-circle-w`,
    arrow_double_e_w: `${arrowFolder}/arrow-double-e-w`,
    arrow_double_ended_n_s: `${arrowFolder}/arrow-double-ended-n-s`,
    arrow_double_ended_ne_sw: `${arrowFolder}/arrow-double-ended-ne-sw`,
    arrow_double_ended_nw_se: `${arrowFolder}/arrow-double-ended-nw-se`,
    arrow_double_ended_w_e: `${arrowFolder}/arrow-double-ended-w-e`,
    arrow_double_n_s: `${arrowFolder}/arrow-double-n-s`,
    arrow_double_ne_sw: `${arrowFolder}/arrow-double-ne-sw`,
    arrow_double_nw_se: `${arrowFolder}/arrow-double-nw-se`,
    arrow_double_s_n: `${arrowFolder}/arrow-double-s-n`,
    arrow_double_se_nw: `${arrowFolder}/arrow-double-se-nw`,
    arrow_double_sw_ne: `${arrowFolder}/arrow-double-sw-ne`,
    arrow_double_w_e: `${arrowFolder}/arrow-double-w-e`,
    arrow_e: `${arrowFolder}/arrow-e`,
    arrow_hook_2_e: `${arrowFolder}/arrow-hook-2-e`,
    arrow_hook_2_w: `${arrowFolder}/arrow-hook-2-w`,
    arrow_hook_e: `${arrowFolder}/arrow-hook-e`,
    arrow_hook_w: `${arrowFolder}/arrow-hook-w`,
    arrow_n: `${arrowFolder}/arrow-n`,
    arrow_ne: `${arrowFolder}/arrow-ne`,
    arrow_nw: `${arrowFolder}/arrow-nw`,
    arrow_omni_directional: `${arrowFolder}/arrow-omni-directional`,
    arrow_omni_directional_two: `${arrowFolder}/arrow-omni-directional-2`,
    arrow_s: `${arrowFolder}/arrow-s`,
    arrow_se: `${arrowFolder}/arrow-se`,
    arrow_square_e: `${arrowFolder}/arrow-square-e`,
    arrow_square_n: `${arrowFolder}/arrow-square-n`,
    arrow_square_s: `${arrowFolder}/arrow-square-s`,
    arrow_square_w: `${arrowFolder}/arrow-square-w`,
    arrow_sw: `${arrowFolder}/arrow-sw`,
    arrow_w: `${arrowFolder}/arrow-w`,
    caret_circle_e: `${arrowFolder}/caret-circle-e`,
    caret_circle_n: `${arrowFolder}/caret-circle-n`,
    caret_circle_s: `${arrowFolder}/caret-circle-s`,
    caret_circle_w: `${arrowFolder}/caret-circle-w`,
    chevron_e: `${arrowFolder}/chevron-e`,
    chevron_n: `${arrowFolder}/chevron-n`,
    chevron_s: `${arrowFolder}/chevron-s`,
    chevron_w: `${arrowFolder}/chevron-w`,
}

export const FieldGroupIcons = {
    ...uiIcons,
    ...timeIcons,
    ...businessIcons,
    ...securityIcons,
    ...peopleIcons,
    ...devicesIcons,
    ...educationIcons,
    ...mediaIcons,
    ...medicalIcons,
    ...navigationIcons,
    ...transportIcons,
    ...travelIcons,
    ...weatherIcons,
    ...arrowIcons,
    ...audioIcons,
    ...beautyIcons,
    ...christmasIcons,
    ...communicationIcons,
    ...connectivityIcons,
    ...drinksIcons,
    ...ecommerceIcons,
    ...environmentIcons,
    ...filesIcons,
    ...foodIcons,
    ...furnitureIcons,
    ...identityIcons,
    ...imageEditingIcons,
    ...landmarksIcons,
    ...movieIcons,
    ...politicsIcons,
    ...prideIcons,
    ...spaceIcons,
    ...sportIcons,
}
